package com.demco.rest.dto

import kotlinx.serialization.Serializable

@Serializable
data class LeagueDTO(
  val name: String,
  val qbs: Int,
  val rbs: Int,
  val wrs: Int,
  val tes: Int,
  val flex: Int,
  val kicker: Int,
  val def: Int,
  val ppPassYd: Double,
  val ppPassTd: Int,
  val ppPass2pt: Int,
  val ppPassInt: Int,
  val ppPassPick6: Int,
  val ppRushYd: Double,
  val ppRushTd: Int,
  val ppRush2pt: Int,
  val ppRecRecep: Double,
  val ppRecYd: Double,
  val ppRecTd: Int,
  val ppRec2pt: Int,
  val ppFg0_19: Int,
  val ppFg20_29: Int,
  val ppFg30_39: Int,
  val ppFg40_49: Int,
  val ppFg_50: Int,
  val ppPat: Int,
  val ppFgMissed: Int,
  val fgMissedMax: Int,
  val ppPatMissed: Int,
  val ppDefTd: Int,
  val ppDefPtsAllowed0: Int,
  val ppDefPtsAllowed1_6: Int,
  val ppDefPtsAllowed7_13: Int,
  val ppDefPtsAllowed14_20: Int,
  val ppDefPtsAllowed21_27: Int,
  val ppDefPtsAllowed28_34: Int,
  val ppDefPtsAllowed35: Int,
  val ppDef4thDownStop: Int,
  val ppDefSack: Int,
  val ppDefInterception: Int,
  val ppDefFumbleRecovery: Int,
  val ppDefSafety: Int,
  val ppDefForcedFumble: Int,
  val ppDefBlockedKick: Int,
  val ppSptTd: Int,
  val ppSptForcedFumble: Int,
  val ppSptFumbleRecovery: Int,
  val ppFumbleTd: Int,
  val ppFumbleLost: Int,
  val playoffWeek: Int,
  val playoffTeams: Int,
)
