version: '3.1'

services:
  db:
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password

  demco-ff-api:
    build: ..
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: test
      DB_PASSWORD: password