version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: password
    healthcheck:
      test: pg_isready -U test -d demco_ff
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"

  demco-ff-api:
    build: ..
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: test
      DB_PASSWORD: password

  playwright-tests:
    image: mcr.microsoft.com/playwright:focal
    working_dir: /integration
    volumes:
      - ./:/integration
    command: bash -c "npm config set update-notifier false && npx playwright test"
    depends_on:
      - demco-ff-api